manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/nickconway
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: leader-key
      import: app/west.yml
  self:
    path: config
